include:
    - project: "epi2melabs/ci-templates"
      file: "push-github.yaml"
    - project: "epi2melabs/ci-templates"
      file: "push-conda.yaml"

image: ${UBUNTUIMAGE}:20.04

.prep-image: &prep-image |
    export DEBIAN_FRONTEND=noninteractive
    apt update -qq
    apt install -y --no-install-recommends make wget python3-all-dev python3-venv 


stages:
    - test
    - build
    - prerelease
    - release
    - postrelease

# Insist that the version in __init__.py matches the git tag
.check-versions: &check-versions |
    PYVER="v"$(grep "__version__ = " ${CI_PROJECT_NAME}/__init__.py | awk '{gsub("\"","",$3); print $3}')
    TAGVER=${CI_COMMIT_TAG}
    if [[ "${PYVER}" != "${TAGVER}" ]]; then
        echo "Mismatching TAG and PACKAGE versions:"
        echo " -     TAG:'$TAGVER'"
        echo " - PACKAGE:'$TAGVER'"
        exit 1
    else
        echo "TAG and PACKAGE versions agree: '${PYVER}'"
    fi

# Insist a CHANGELOG entry has been made for tags
.check-changelog: &check-changelog |
    TAGVER=${CI_COMMIT_TAG}
    MATCHES=$(grep -c "## \[${TAGVER}\]" CHANGELOG.md || exit 0)
    if [[ "${MATCHES}" != "1" ]]; then
        echo "Expected one match to '${CI_COMMIT_TAG}' in CHANGELOG, found ${MATCHES}"
        exit 1
    else
        echo "Found CHANGELOG.md entry for tag"
    fi

test:
    stage: test
    script:
        - *prep-image
        - make test
        - make docs
        - make sdist
    artifacts:
        paths:
            - aplanat_demo_report.html
            - dist/*.tar.gz

deploy-checks:
    stage: prerelease
    script:
        - *check-versions
        - *check-changelog
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/'

deploy:pypi:
    stage: release
    script:
        - *prep-image
        - make pypi_build/bin/activate
        - source pypi_build/bin/activate
        - twine upload --non-interactive dist/*.tar.gz
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/'

conda:
    extends:
        - .deploy-conda
    before_script:
        - *prep-image
        - export CONDA_PKG=${CI_PROJECT_NAME}
        - export CONDA_PKG_VERSION=${CI_COMMIT_TAG/v/}
        - cd conda

conda-mac:
    extends:
        - .deploy-conda-mac
    before_script:
        - export CONDA_PKG=${CI_PROJECT_NAME}
        - export CONDA_PKG_VERSION=${CI_COMMIT_TAG/v/}
        - cd conda

deploy:trigger:
    stage: postrelease
    trigger: epi2melabs/nanolabs
    rules:
        - if: '$CI_COMMIT_TAG =~ /^v[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+$/'
