
# this doesn't work
# {% set data = load_setup_py_data() %}

package:
  name: {{ environ.get('CONDA_PKG') }}
  version: {{ environ.get('CONDA_PKG_VERSION') }}

source:
    path: ../

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv"
  noarch: python

requirements:
  host:
    - pip
    - python
  run:
    - bokeh < 3.0.0
    - icon_font_to_png
    - markdown
    - numpy
    - pandas >=1.0.3
    - pillow
    - python
    - scipy
    - si-prefix
    - sigfig

test:
  imports:
    - aplanat

about:
  home: "https://github.com/epi2me-labs/aplanat"
  license: Mozilla Public License 2.0 
  license_family: OTHER
  license_file: LICENSE.md
  summary: "Bokeh plotting API, with bio-focussed extras."
  doc_url: https://github.com/epi2me-labs/aplanat
  dev_url: https://github.com/epi2me-labs/aplanat 

extra:
  recipe-maintainers:
    - cjw85

